# File: .github/workflows/template-sync.yml

on:
  schedule:
  - cron:  "0 0 1 * *"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: cockpit-project/starter-kit
          upstream_branch: main
